docs_dir: 'Documentation'
site_dir: '.Build/docs'

# Site configuration
site_name: Handlebars extension for TYPO3 CMS
site_url: https://cps-it.github.io/handlebars/
site_description: Documentation of EXT:handlebars
site_author: Elias Häußler

# Repository configuration
repo_url: https://github.com/CPS-IT/handlebars
edit_uri: edit/master/Documentation/

# Copyright
copyright: Copyright &copy; 2020 - %current_year% <a href="mailto:e.haeussler@familie-redlich.de" target="_blank">Elias Häußler</a>

# Navigation
nav:
  - Home: index.md
  - Getting started:
    - Installation: install.md
    - Configuration: configuration.md
    - Usage: usage.md
  - 'Rendering concept':
    - Components: rendering/components.md
    - 'Rendering process': rendering/rendering-process.md
    - 'Register components': rendering/register-components.md
  - About:
    - Development: develop.md
    - License: license.md

# Theme configuration
theme:
  name: material
  custom_dir: Documentation/theme
  features:
    - navigation.sections
    - navigation.top
  palette:
    accent: orange
  font:
    text: Proxima Nova
    code: Inconsolata
  logo: assets/img/fr.png
  favicon: assets/img/favicon.png
use_directory_urls: false
extra_css:
  - assets/css/theme.css

extra:
  repository:
    url: https://github.com/CPS-IT/handlebars
    blob: https://github.com/CPS-IT/handlebars/blob/master
  link:
    t3_explained: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us

# Plugins and extensions
plugins:
  - search
  - localsearch
  - git-revision-date
  - macros
  - exclude:
      glob:
        - build/*
        - __pycache__/*
        - hooks.py
  - mkdocs-simple-hooks:
      hooks:
        on_config: 'Documentation.hooks:apply_copyright_year'
markdown_extensions:
  - attr_list
  - markdown.extensions.admonition
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
        - name: typo3_typoscript
          lang: typoscript
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
