<?php

declare(strict_types=1);

/*
 * This file is part of the TYPO3 CMS extension "handlebars".
 *
 * Copyright (C) 2021 Elias Häußler <e.haeussler@familie-redlich.de>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

namespace Fr\Typo3Handlebars\Generator\Definition;

use Fr\Typo3Handlebars\Presenter\AbstractPresenter;
use Fr\Typo3Handlebars\Presenter\PresenterInterface;
use Laminas\Code\Generator\DocBlock\Tag\GenericTag;
use Laminas\Code\Generator\DocBlockGenerator;
use Laminas\Code\Generator\MethodGenerator;

/**
 * PresenterClassDefinition
 *
 * @author Elias Häußler <e.haeussler@familie-redlich.de>
 * @license GPL-2.0-or-later
 * @internal
 */
final class PresenterClassDefinition extends AbstractClassDefinition
{
    public function build(string $name, array $options = []): array
    {
        return [
            'extendedclass' => AbstractPresenter::class,
            'methods' => [
                $this->buildMethodGenerator($name, $options),
            ],
            'docblock' => DocBlockGenerator::fromArray([
                'shortdescription' => sprintf('Handlebars presenter "%s".', $name),
                'longdescription' => 'This class is auto-generated by EXT:handlebars.',
                'tags' => [
                    new GenericTag('see', $this->decorateGeneratorMethod()),
                ],
            ])->setWordWrap(false),
        ];
    }

    /**
     * @param string $name
     * @param array<string, mixed> $options
     * @return MethodGenerator
     */
    private function buildMethodGenerator(string $name, array $options = []): MethodGenerator
    {
        $methodGenerator = $this->getMethodGeneratorFromReflection(PresenterInterface::class, 'present');
        $methodGenerator->removeDocBlock();

        $providerResponseClassName = $options['providerResponseClassName'];
        $timestamp = $options['timestamp'] ?? time();

        // Set method body
        $methodGenerator->setBody(
            <<<BODY
if (!(\$data instanceof $providerResponseClassName)) {
    throw new \Fr\Typo3Handlebars\Exception\UnableToPresentException('Received unexpected response from provider.', $timestamp);
}

\$renderData = [
    // TODO: Implement Handlebars presenter "$name".
];

// TODO: Define template path
return \$this->renderer->render('path/to/template', \$renderData);
BODY
        );

        return $methodGenerator;
    }
}
