services:
  _defaults:
    autowire: true
    autoconfigure: true

  Fr\Typo3Handlebars\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'

handlebars:
  variables: []
  view:
    templateRootPaths: []
    partialRootPaths: []
