services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\Typo3Handlebars\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'

  Fr\Typo3Handlebars\Cache\CacheInterface:
    alias: 'handlebars.cache'
  Fr\Typo3Handlebars\Renderer\RendererInterface:
    alias: 'handlebars.renderer'
  Fr\Typo3Handlebars\Renderer\Template\TemplateResolverInterface:
    alias: 'handlebars.template_resolver'

  # Template
  handlebars.template_resolver:
    class: 'Fr\Typo3Handlebars\Renderer\Template\HandlebarsTemplateResolver'
    arguments:
      $templateRootPaths: '@handlebars.template_paths.template_root_paths'

  handlebars.partial_resolver:
    class: 'Fr\Typo3Handlebars\Renderer\Template\HandlebarsTemplateResolver'
    arguments:
      $templateRootPaths: '@handlebars.template_paths.partial_root_paths'

  handlebars.template_paths:
    class: 'Fr\Typo3Handlebars\Renderer\Template\TemplatePaths'
  handlebars.template_paths.template_root_paths:
    parent: 'handlebars.template_paths'
    arguments:
      $type: 'template_root_paths'
  handlebars.template_paths.partial_root_paths:
    parent: 'handlebars.template_paths'
    arguments:
      $type: 'partial_root_paths'

  # Handlebars Helper
  Fr\Typo3Handlebars\Renderer\Helper\VarDumpHelper:
    tags:
      - name: handlebars.helper
        identifier: 'varDump'
        method: 'evaluate'

  # Cache
  cache.handlebars:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['handlebars']

handlebars:
  default_data: []
  template:
    template_root_paths: []
    partial_root_paths: []
