services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Fr\Typo3Handlebars\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'

  Fr\Typo3Handlebars\Cache\Cache:
    alias: 'handlebars.cache'
  Fr\Typo3Handlebars\Renderer\Renderer:
    alias: 'handlebars.renderer'
  Fr\Typo3Handlebars\Renderer\Template\TemplateResolver:
    alias: 'handlebars.template_resolver'

  # Template
  handlebars.template_resolver:
    class: 'Fr\Typo3Handlebars\Renderer\Template\HandlebarsTemplateResolver'

  # Cache
  cache.handlebars:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['handlebars']

handlebars:
  variables: []
  view:
    templateRootPaths: []
    partialRootPaths: []
