name: CGL
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2, composer-require-checker, composer-unused

      # Validation
      - name: Validate composer.json
        run: composer validate

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --no-plugins

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check --config-file dependency-checker.json
      - name: Re-install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer lint:composer -- --dry-run
      - name: Lint Editorconfig
        run: .Build/bin/ec -e .Build
      - name: Lint PHP
        run: composer lint:php -- --dry-run
      - name: Lint TypoScript
        run: composer lint:typoscript -- --fail-on-warnings

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
