name: CGL
on: [push, pull_request]

jobs:
  cgl:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2

      # Validation
      - name: Validate composer.json
        run: composer validate --no-check-lock

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress

      # Linting
      - name: Lint composer.json
        run: composer lint:composer -- --dry-run
      - name: Lint PHP
        run: composer lint:php -- --dry-run
      - name: Lint TypoScript
        run: composer lint:typoscript -- --fail-on-warnings

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github
