name: Documentation
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install \
            mkdocs-material \
            Pygments \
            mkdocs-git-revision-date-plugin \
            mkdocs-localsearch \
            mkdocs-exclude \
            mkdocs-macros-plugin \
            mkdocs-simple-hooks
      - run: mkdocs gh-deploy --site-dir .Build/docs --force
